"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['./data/dutch.csv', './images/card_front.png', './images/card_back.png', './images/wrong.png', './images/right.png']
OPTIONS = {'packages': ['tkinter', 'pandas', 'random']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
